//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsultaCRUD.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Consulta
    {
        public int Id_consulta { get; set; }
        [Display(Name = "Nome do Paciente")]
        public Nullable<int> Id_paciente { get; set; }
        [Display(Name = "Nome do Exame")]
        public Nullable<int> ID_exame { get; set; }
        [Required]
        [DataType(DataType.DateTime)]
        [Display(Name = "Data da Consulta")]
        public Nullable<System.DateTime> Data_consulta { get; set; }

        public virtual Exame Exame { get; set; }
        public virtual Paciente Paciente { get; set; }
    }
}
