//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsultaCRUD.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Exame
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Exame()
        {
            this.Consulta = new HashSet<Consulta>();
        }
    
        public int Id_ex { get; set; }
        [Required]
        [Display(Name = "Nome do Exame")]
        public string Nome_ex { get; set; }
        [Required]
        [StringLength(256)]
        [Display(Name = "Descrição")]
        public string Descicao { get; set; }
        [Display(Name = "Observações")]
        [StringLength(1000)]
        [DisplayFormat(NullDisplayText = "Sem Observação")]
        public string Observacao { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Consulta> Consulta { get; set; }
    }
}
