//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsultaCRUD.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web.Mvc;

    public partial class Paciente
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Paciente()
        {
            this.Consulta = new HashSet<Consulta>();
        }
        
        public int Id_pac { get; set; }
        [Required]
        [StringLength(100)]
        [Display(Name = "Nome Completo")]
        //[Remote(action: "VerifyName", controller: "PacientesController")]
        public string Nome_pac { get; set; }
        [Required]
        [StringLength(11)]
        [MaxLength(11)]
        [MinLength(11)]
        [Display(Name = "CPF")]
        public string Cpf_pac { get; set; }
        [Required]
        [DataType(DataType.Date)]
        [Display(Name = "Data de Nascimento")]
        public System.DateTime Data_nasc_pac { get; set; }
        [Required]
        [Display(Name = "Sexo")]
        public string Sexo_pac { get; set; }
        [Required]
        [Phone]
        [Display(Name = "Telefone")]
        public string Telefone_pac { get; set; }
        [Required]
        [EmailAddress]
        //[Remote(action: "VerifyEmail", controller: "Users")]
        [Display(Name = "E-mail")]
        public string Email_pac { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Consulta> Consulta { get; set; }
    }
}
